### ISSUE TITLE
如何安装与启动

### ISSUE THREAD

**Issue by kenberkeley** [kenberkeley/react-demo#1]
> 使用 `cnpm` 替代 `npm` 可大大减少安装依赖耗时：  
> `npm install -g cnpm --registry=https://registry.npm.taobao.org`

首先，您需要打开两个命令窗口，记为窗口 A  和窗口 B
窗口 A 用于启动前端开发服务器，窗口 B 用于启动后端 RESTful API  

假设您想在 `/Users/ken/` 目录下存放项目代码，那就**分别**在窗口 A B 敲下：`cd /Users/ken` 切换到该路径  

之后，在窗口 B 中敲下：

```
$ git clone https://github.com/kenberkeley/msg-board-api.git`
### 拉取代码...

$ cd msg-board-api
$ cnpm i
### 安装依赖...

$ npm start
```

同样地，在窗口 A 中敲下：

```
$ git clone https://github.com/kenberkeley/react-demo.git
$ cd react-demo
$ cnpm i
$ npm start
```

编译完毕后，默认情况下浏览器会自动弹出并访问 `localhost:9090`

**Comment by SharonLucky** [comment]
哪两个窗口？

**Comment by kenberkeley** [comment]
@SharonLucky 随便打开两个命令窗

**Comment by ruizhengyun** [comment]
按照作者的所表述的方法，做个下载-安装包-然后start，react-demo文件start后报错。
错误显示：
events.js:160
      throw er; // Unhandled 'error' event
      ^

**Comment by taditang** [comment]
显示需要across-env, 但淘宝的cnpm没找到这个库

**Comment by kenberkeley** [comment]
@taditang 
是 `cross-env` 哦

**Comment by taditang** [comment]
恩, 已经发现了

**Comment by erdongjun** [comment]
为什么npm start 控制台也没报错  一直是404呢?

**Comment by kenberkeley** [comment]
没有报错的话，爱莫能助啊亲。。。

**Comment by erdongjun** [comment]
@kenberkeley 我是按照你的教程一步步走的 没有任何的报错 api服务器也启动了,但是在demo编译完成时  控制台打印的access urls  端口 是9001  浏览器打开的是我在配置文件中修改的 9000端口 这是为什么

**Comment by kenberkeley** [comment]
抱歉，现在我在电影院看『我不是潘金莲』，回家再帮您解决。

**Comment by erdongjun** [comment]
@kenberkeley 打扰了 ,我再研究下,  您先忙.

**Comment by erdongjun** [comment]
抱歉 重新下载安装了 没问题了 ,谢谢您了,

**Comment by kenberkeley** [comment]
@Davau 解决了就好，嘻嘻

**Comment by jimwmg** [comment]
$ npm start

> msg-board-api@0.1.0 start F:\04yuannianwork\08redux\ken\msg-board-api
> node app.js

[AutoMount] delete /msg/:msgId
[AutoMount] put /msg/:msgId
[AutoMount] get /msg/:msgId
[AutoMount] get /logout
[AutoMount] post /login
[AutoMount] get /user/
[AutoMount] post /msg/
[AutoMount] get /msg/
[INFO] Msg board RESTful API listening at localhost:8989
[LOG] GET /
{ _code: 404, _msg: 'Page not found' }
[LOG] GET /favicon.ico
{ _code: 404, _msg: 'Page not found' }

为啥是8989 好难过,不过写的文章真好

**Comment by kenberkeley** [comment]
@jimwmg https://github.com/kenberkeley/msg-board-api/blob/master/app.js#L42

**Comment by jimwmg** [comment]
好用了好用了   谢谢,谢谢  啊哈哈

**Comment by jimwmg** [comment]
爱上您啦  写的demo和实例太好了,源码看得我心花路放  谢谢谢谢

**Comment by kenberkeley** [comment]
我已经弃 React 坑了，希望大家也转战 Vue 2：https://github.com/kenberkeley/vue2-scaffold

**Comment by jimwmg** [comment]
公司最近要用这个,所以来学,vue以后有机会肯定也要学的

**Comment by romantiskt** [comment]
建议答主把这个加入到readme中

**Comment by Niulimei** [comment]
显示需要across-env, 但淘宝的cnpm没找到这个库  

这个问题解决了吗？我这边也是这个问题啊！！！

**Comment by Niulimei** [comment]
@taditang

**Comment by kenberkeley** [comment]
@Niulimei https://cnpmjs.org/package/cross-env

**Comment by Niulimei** [comment]
多谢 @kenberkeley

**Comment by wasabi1215** [comment]
Cloning into 'msg-board-api'...
fatal: unable to access 'https://github.com/kenberkeley/msg-board-api.git/': Emp                                                                                            ty reply from server
