### ISSUE TITLE
部署到正式环境的问题

### ISSUE THREAD

**Issue by pasBone** [kenberkeley/react-demo#10]
就是部署到正式环境，运行npm run build之后，就不用再运行react-demo 下面的 npm start 了吧，但是这样网站打不开了啊。我看里面的代码， 只有dev环境下才有 9000 端口这个服务啊， 该怎么办呢？

**Comment by kenberkeley** [comment]
请参考 README 中的 [部署](https://github.com/kenberkeley/react-demo/blob/master/README.md#deployment)
