### ISSUE TITLE
dev环境和正式部署环境的差异

### ISSUE THREAD

**Issue by pasBone** [kenberkeley/react-demo#11]
在dev环境下，可以访问 http://localhost:9000/msg或者http://localhost:9000/todo等等，并且刷新浏览器依然可以访问，有点不像单页的感觉，但实际是单页，但是可以刷新，前进和后退
在prod环境下，不能直接输入网址http://localhost:9000/msg 访问，可以前进后退，但是不能刷新，请问是什么情况呢，怎样才能做到像dev环境下那样可以刷新呢

**Comment by kenberkeley** [comment]
这需要 [connect-history-api-fallback](https://github.com/bripkens/connect-history-api-fallback) 这类 Package 提供支持（若是直接使用 Nginx 部署，参见[这里](http://readystate4.com/2012/05/17/nginx-and-apache-rewrite-to-support-html5-pushstate/)），否则最好使用 [hashbang 模式](https://github.com/vuejs/vue-router/blob/1.0/docs/zh-cn/options.md#hashbang)
