### ISSUE TITLE
找不到 'history/lib/createBrowserHistory'

### ISSUE THREAD

**Issue by leecz** [kenberkeley/react-demo#12]
ERROR in ./src/redux/store/syncHistoryWithStore.js
Module not found: Error: Cannot resolve module 'history/lib/createBrowserHistory' in 

想知道为什么是 lib 下面的 createBrowserHistory， 而不是直接 history 下面的？

**Comment by kenberkeley** [comment]
您使用的应该是最新版本的 `history`，而本 demo 使用的是 `v2.x`
详见：https://github.com/mjackson/history/blob/v2.x/docs/GettingStarted.md#minimizing-your-build

**Comment by leecz** [comment]
是的，我都用的最新版的，原来如此。我去掉lib，报了一个其他的错误，估计也是 history 版本的问题。现在我不使用 useRouterHistory 和 createBrowserHistory 来创建 history 了，直接用 react-router 的 browserHistory ，能 work 。想知道两者的区别。

**Comment by kenberkeley** [comment]
建议自行搜索相关资料
