### ISSUE TITLE
很多组件的构造函数中有 this.state = XXX,请问这样和"不要直接手动修改state"矛盾吗？

### ISSUE THREAD

**Issue by LittleTheFu** [kenberkeley/react-demo#18]
你好，我刚刚接触react。
教程上是说不要修改state，而是返回变化后的state的副本。
但是如下代码有     this.state = { inputVal: '' }
```
export default class TodoInput extends Component {
  constructor (props) {
    super(props)
    this.state = { inputVal: '' }
    this.handleChange = handleChange.bind(this)
  }
...
}
```

**Comment by kenberkeley** [comment]
这就是所谓的 **本地状态**

**Comment by kenberkeley** [comment]
Redux 中的 `state` 与各组件内部的 `state` 并不是同一个 `state`

**Comment by LittleTheFu** [comment]
谢谢，我刚才看了官方的sample，他也是这么做的。
[官方教程](https://facebook.github.io/react/tutorial/tutorial.html)

```
class Square extends React.Component {
  constructor() {
    super();
    this.state = {
      value: null,
    };
  }
  ...
}
```

我又顺着 **本地状态** 搜索到了一篇文章，希望对后来人有帮助。
[Best Practices for Component State in React.js](http://brewhouse.io/blog/2015/03/24/best-practices-for-component-state-in-reactjs.html)

非常感谢您的及时解答。

**Comment by kenberkeley** [comment]
还有一篇：[You Might Not Need Redux](https://medium.com/@dan_abramov/you-might-not-need-redux-be46360cf367)

**Comment by LittleTheFu** [comment]
谢谢。
