### ISSUE TITLE
在ie浏览器上面兼容性 ？

### ISSUE THREAD

**Issue by cl1069573062** [kenberkeley/react-demo#19]
在本机使用ie 11 打开。页面无显示，react在ie 11 都无法兼容吗？

**Comment by kenberkeley** [comment]
控制台错误信息？

**Comment by cl1069573062** [comment]
SCRIPT438: 对象不支持“startsWith”属性或方法

**Comment by kenberkeley** [comment]
请自行引入 [es6-shim](https://github.com/paulmillr/es6-shim)
