### ISSUE TITLE
React 升级 15.4.0+ react-hot-loader导致服务无法启动

### ISSUE THREAD

**Issue by stefaniepei** [kenberkeley/react-demo#20]
![image](https://cloud.githubusercontent.com/assets/1124923/20589981/097180e6-b25b-11e6-920d-0509e4bafec6.png)

**Comment by kenberkeley** [comment]
#13

**Comment by kenberkeley** [comment]
建议降版本

**Comment by stefaniepei** [comment]
好的，非常感谢您的分享！
