### ISSUE TITLE
import后面加;报错

### ISSUE THREAD

**Issue by calcyu** [kenberkeley/react-demo#22]
```
ERROR in ./src/app.js

  error  semi  Extra semicolon
  E:\wanmagu.com\React-weixin\react-seller\src\app.js:2:26
  import React from 'react';
                            ^


✖ 1 problem (1 error, 0 warnings)
```
为什么我在import xxx 后面加了```;```会报上面这个错误，不晓得出错的原因在哪里

**Comment by kenberkeley** [comment]
https://github.com/eslint/eslint

**Comment by Yakima-Teng** [comment]
Because code style checking was enabled by default.

**Comment by calcyu** [comment]
@Yakima-Teng 可以取消这个检查吗？我有一些代码全是有;的，不然要手动把所有;去除才能正常使用。

**Comment by kenberkeley** [comment]
@calcyu 
https://github.com/kenberkeley/react-demo/blob/master/build/webpack.base.conf.js#L77 中去掉 `eslint`

**Comment by calcyu** [comment]
@kenberkeley 谢谢，我正在吭ESLINT配置文件说明，准备搜索ESLINT与WEBPACK如何配置，你的消息就来了。 ：）

**Comment by kenberkeley** [comment]
@calcyu 不过我不建议去掉代码风格检查

**Comment by Yakima-Teng** [comment]
@calcyu 代码检查有很多好处的，一些常见的诸如变量未定义什么之类的错误可以通过这些提示知道，如果你之前有分号的代码和现在没有分号的代码的路径有明显的不同，也可以通过修改.eslintignore这个文件，增加不需要代码检查的路径/文件：
https://github.com/kenberkeley/react-demo/blob/master/.eslintignore
