### ISSUE TITLE
如何使用proxy

### ISSUE THREAD

**Issue by rockyuse** [kenberkeley/react-demo#23]
使用http-proxy-middleware没有生效
`app.use('/canvas', proxy({target: 'http://10.109.4.25', changeOrigin: true}));`
请问是哪里的配置给阻断了呢？

**Comment by kenberkeley** [comment]
https://github.com/kenberkeley/react-demo/blob/master/src/services/xhr/config.js#L5

**Comment by kenberkeley** [comment]
当前 demo 是直连 RESTful API 的
