### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by supwjm** [kenberkeley/react-demo#24]
您好，npm install --no-bin-link 安装模块时报错了： Maximum call stack size exceeded

![qq 20161216100945](https://cloud.githubusercontent.com/assets/9331095/21249325/2e0f0a94-c378-11e6-97a1-fbf7b9f08467.png)

能帮忙看一下吗

**Comment by kenberkeley** [comment]
`npm3` 毋须使用 `--no-bin-link`，请直接 `npm install` 即可
