### ISSUE TITLE
react-demo目录里npm install之后好像安装依赖不完全

### ISSUE THREAD

**Issue by Richardo8** [kenberkeley/react-demo#25]
![image](https://cloud.githubusercontent.com/assets/23549289/21417108/317da93a-c853-11e6-9a75-0e0f6070720c.png)
如图 没找到模块 我看了一下配置文件中好多需要的依赖在node_modules中都没有 这是怎么回事 重新install了好几次了

**Comment by kenberkeley** [comment]
我看了一下源码：https://github.com/kenberkeley/react-demo/blob/master/package.json
依赖并没有丢失

因此，建议您：
```
rm -rf node_modules
npm i cnpm -g
cnpm i
```

**Comment by Richardo8** [comment]
![image](https://cloud.githubusercontent.com/assets/23549289/21417336/b0f0b396-c854-11e6-8f01-d9f2f3120b56.png)
依然还是存在这种问题 node_modules中缺少一些modules  我是直接clone过来的

**Comment by kenberkeley** [comment]
建议手动 `cnpm i nyan-progress-webpack-plugin -S`

**Comment by Richardo8** [comment]
嗯 我大概对照package.json看了一下 按说应该有50多个modules 实际安装了30多个 尤其像是babel这些都没有 是不是需要之前就已经全局安装过？ 如果最后实在不行就只能手动一个个安装

**Comment by kenberkeley** [comment]
不可能会有那么麻烦的事情哦，您确定您是使用 `cnpm` 安装的？

**Comment by Richardo8** [comment]
对 按着您的教程一步步来的 就出现这种问题 删掉node_module文件夹改用cnpm也是这样

**Comment by kenberkeley** [comment]
那我也表示爱莫能助了，毕竟我刚刚也重新 clone 然后安装运行，没有发现您所说的这个问题

**Comment by Richardo8** [comment]
这个会和npm版本有关吗 
![image](https://cloud.githubusercontent.com/assets/23549289/21417585/96f7dfbc-c856-11e6-9211-aa70fc264dad.png)
我的npm版本是3.10.8

**Comment by kenberkeley** [comment]
若您使用的是 `cnpm`，则跟 `npm` 的版本无关

**Comment by Richardo8** [comment]
![image](https://cloud.githubusercontent.com/assets/23549289/21417752/b328d8b6-c857-11e6-8a5e-62454450ff3f.png)
刚才的是我使用bash  这回我用cmd   cnpm i 我发现dependencies的都安装了 但是devDependencies的没有安装

**Comment by kenberkeley** [comment]
要不换个 [git bash](https://git-for-windows.github.io/) 试一试？

**Comment by Richardo8** [comment]
![image](https://cloud.githubusercontent.com/assets/23549289/21418009/5c72ff7c-c859-11e6-9acd-e60e615c10a5.png)
一开始用的就是git bash 这会又试了一次 还是不对 devDependencies 这里边的依赖好像都没有
