### ISSUE TITLE
Redux是把所有的数据都传递过来么，不是页面需要什么数据就传递什么数据么？如果是前者，会有性能问题；如果是后者，怎么做到的，通过Reducer？

### ISSUE THREAD

**Issue by hiddaorear** [kenberkeley/react-demo#27]
具体代码如下： 

// 情况2：处于 /msg/modify/:msgId，且 state 中 msgs 不为空
    
    if (msgs.length) {
      // Small Fish Wang: 所有的数据都传递过来了，然后从中自己挑选，这里使用了filter方法
      // 我觉得这个应该是Redux中的Reducer来实现的，要不然每个地方都传递所有的数据，数据量大的情况下，会有性能问题。
      // 这个地方也用解构，用得真灵活而方便。

      let nextState = msgs.filter(({ id }) => id === msgId)[0]
      if (!nextState || nextState.author !== username) {
        return this.handleIllegal()
      }

      return this.setState(nextState)
    }

**Comment by kenberkeley** [comment]
其实都是传个引用而已，不会有什么性能问题的。。。

**Comment by hiddaorear** [comment]
总感觉按需取数据会严谨些。在数据很多的情况下，这么做数据不好管理呀。

**Comment by kenberkeley** [comment]
对的，没错

**Comment by hiddaorear** [comment]
只能这么干么？

**Comment by kenberkeley** [comment]
（抱歉刚才开会去了）
组件按需传数据是较好的实践

还有一点需要指出：当前这个 `react-demo` 可能已经过时了，实际开发可参考很火的 [Next.js](https://github.com/zeit/next.js/)
中小型项目我一般不推荐 Redux，因为开发效率实在是太低了。。。

**Comment by kenberkeley** [comment]
现在我主要使用 [vue-demo](https://github.com/kenberkeley/vue-demo) 作为实际项目的开发
该项目也是一直持续维护的，而且文档相对比较完善

**Comment by hiddaorear** [comment]
谢谢你！对于Redux，我也是这么认为的，原本很一步到位的事情，需要写一堆东西，很绕。有其他成熟的方案推荐么？

**Comment by kenberkeley** [comment]
https://github.com/kenberkeley/vue-demo

**Comment by hiddaorear** [comment]
在做React相关的项目，以前也用过AngularJS，剩下Vue没有用过，等把React学得够用了，回头来看Vue的。
