### ISSUE TITLE
run install错误信息

### ISSUE THREAD

**Issue by chenming7583** [kenberkeley/react-demo#28]
Error: node-sass@3.13.1 postinstall: `node scripts/build.js`
9601 verbose stack Exit status 1
9601 verbose stack     at EventEmitter.<anonymous> (D:\Program Files\nodejs\node_global\node_modules\npm\lib\utils\lifecycle.js:279:16)
9601 verbose stack     at emitTwo (events.js:106:13)
9601 verbose stack     at EventEmitter.emit (events.js:192:7)
9601 verbose stack     at ChildProcess.<anonymous> (D:\Program Files\nodejs\node_global\node_modules\npm\lib\utils\spawn.js:40:14)
9601 verbose stack     at emitTwo (events.js:106:13)
9601 verbose stack     at ChildProcess.emit (events.js:192:7)
9601 verbose stack     at maybeClose (internal/child_process.js:890:16)
9601 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
9602 verbose pkgid node-sass@3.13.1

**Comment by kenberkeley** [comment]
请使用 `cnpm` 安装依赖
详情请参考 [⊙ 安装](https://kenberkeley.github.io/vue-demo/dist/docs/zh-cn/Getting-started.html)

**Comment by chenming7583** [comment]
好的,谢谢 我看看

 

发件人: bounces+848413-639c-20chenming08=163.com@sgmail.github.com [mailto:bounces+848413-639c-20chenming08=163.com@sgmail.github.com] 代表 Ken Berkeley
发送时间: 2017年2月16日 11:55
收件人: kenberkeley/react-demo <react-demo@noreply.github.com>
抄送: chenming7583 <20chenming08@163.com>; Author <author@noreply.github.com>
主题: Re: [kenberkeley/react-demo] run install错误信息 (#28)

 

请使用 cnpm 安装依赖
详情请参考 ⊙  <https://kenberkeley.github.io/vue-demo/dist/docs/zh-cn/Getting-started.html> 安装
