### ISSUE TITLE
关于componentWillReceiveProps 无限循环问题

### ISSUE THREAD

**Issue by Measy** [kenberkeley/react-demo#29]
handleIllegal() {
        //使用setTimeout防止阻塞跳转
        setTimeout(() => alert('非法访问'))
        location.replace('/msg')

        // 为什么不使用如下代码跳转？
        // this.context.router.replace('/msg')
        // 因为会触发 componentWillReceiveProps 无限循环
    }

请问一下博主为什么this.context.router.replace('/msg')为造成无线循环

**Comment by kenberkeley** [comment]
试一下就知道了呗ㄟ( ▔, ▔ )ㄏ

**Comment by Measy** [comment]
http://stackoverflow.com/questions/36189775/infinite-loop-when-dispatching-in-componentwillreceiveprops   感谢博主详细的注释
