### ISSUE TITLE
react-dome安装问题

### ISSUE THREAD

**Issue by ghost** [kenberkeley/react-demo#3]
@kenberkeley 按照作者的所表述的方法，做个下载-安装包-然后start，react-demo文件start后报错。
错误显示：
events.js:160
throw er; // Unhandled 'error' event
^

Error: listen EADDRINUSE 127.0.0.1:9000
at Object.exports._errnoException (util.js:1007:11)
at exports._exceptionWithHostPort (util.js:1030:20)
at Server._listen2 (net.js:1253:14)
at listen (net.js:1289:10)
at net.js:1399:9
at _combinedTickCallback (internal/process/next_tick.js:77:11)
at process._tickCallback (internal/process/next_tick.js:98:9)
at Module.runMain (module.js:577:11)
at run (node.js:348:7)
at startup (node.js:140:9)
at node.js:463:3

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.2.2
npm ERR! npm v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! react-demo@0.1.0 start: cross-env NODE_ENV=development node build/dev-server.js
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-demo@0.1.0 start script 'cross-env NODE_ENV=development node build/dev-server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-demo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! cross-env NODE_ENV=development node build/dev-server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR! npm bugs react-demo
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! npm owner ls react-demo
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR! /Users/ruizhengyun/dev/rzy_javascript/react/react-demo/npm-debug.log

**Comment by kenberkeley** [comment]
@ruizhengyun 
9000 端口被占用了，换一个吧亲
