### ISSUE TITLE
直接运行不了

### ISSUE THREAD

**Issue by TongDaDa** [kenberkeley/react-demo#32]
"cross-env NODE_ENV=development node build/dev.js",

"cross-env NODE_ENV=development " 前面加这个出错; 取消掉的话下面还出错。

env = process.env.NODE_ENV.trim(); // 当前环境

**Comment by kenberkeley** [comment]
呃 需要 `cnpm i -D cross-env`。。。看来我需要更新一下这个项目了，好久没动了。。。
