### ISSUE TITLE
有些看不明白的地方想请教一下

### ISSUE THREAD

**Issue by ideaviewes** [kenberkeley/react-demo#35]
刚学习react时间不久，在您的项目中有些写法看的不太明白，例如
app.js中的
import store, { history } from 'STORE'
import routes from 'ROUTE'
routes/index.js中
require('COMPONENT/Welcome').default
STORE和ROUTE时自定义的吗？如何来定义他们具体的位置
这种写法很多

**Comment by kenberkeley** [comment]
https://github.com/kenberkeley/react-demo/blob/master/build/webpack.base.conf.js#L45-L55
