### ISSUE TITLE
不能运行...

### ISSUE THREAD

**Issue by TongDaDa** [kenberkeley/react-demo#36]
> react-demo@0.1.0 start F:\works\projects\react-demo-master
> cross-env NODE_ENV=development node build/dev.js

'cross-env' ²»ÊÇÄÚ²¿»òÍâ²¿ÃüÁî£¬Ò²²»ÊÇ¿ÉÔËÐÐµÄ³ÌÐò
»òÅú´¦ÀíÎÄ¼þ¡£

**Comment by kenberkeley** [comment]
建议按照 #1 执行

**Comment by TongDaDa** [comment]
![image](https://cloud.githubusercontent.com/assets/23241188/25265613/80d94bdc-26a0-11e7-8e14-989bb795d897.png)

**Comment by kenberkeley** [comment]
您可以全局安装 `cross-env`：`cnpm i -g cross-env` 后，自己敲命令：
`cross-env NODE_ENV=development node build/dev.js` 测试一下

**Comment by TongDaDa** [comment]
我用npm安装的，没用cnpm

**Comment by kenberkeley** [comment]
没区别

**Comment by TongDaDa** [comment]
可以了，哈哈

**Comment by TongDaDa** [comment]
非常感谢

**Comment by kenberkeley** [comment]
建议使用 `git clone` 而不是下载 zip 代码压缩包，皆因会有编码问题

**Comment by TongDaDa** [comment]
我不运行msg-board-ap也可以啊
