### ISSUE TITLE
开发过程中碰到的问题

### ISSUE THREAD

**Issue by ghost** [kenberkeley/react-demo#4]
@kenberkeley 
问题一：启动文件app.js中
import store, { history } from 'STORE'
import routes from 'ROUTE'
一般我会写
import store, { history } from './index'
import routes from './route'

问题二：
**DEV**和**PROD**意思我清楚，区分开发环境和生产环境，可是我没有看到这个设置

**Comment by kenberkeley** [comment]
问题一：主要取决于您的目录设置。路径别名主要是方便日后的重构
问题二：定义在 `build/webpack.base.conf.js` 最后的 `webpack.DefinePlugin`
