### ISSUE TITLE
感觉不错,可否增加代理

### ISSUE THREAD

**Issue by kkstun** [kenberkeley/react-demo#40]
想vue cli一样的 http-proxy-middleware

**Comment by kenberkeley** [comment]
参考 https://github.com/kenberkeley/vue-demo/blob/master/build/dev.js#L16-L23

**Comment by kkstun** [comment]
请问下,热加载后,修改文件,不能自动更新浏览器? 我之前用的是vue

**Comment by kenberkeley** [comment]
支持热更新，无需刷新整个页面
