### ISSUE TITLE
发现个小问题

### ISSUE THREAD

**Issue by zwz111** [kenberkeley/react-demo#5]
在留言的添加和修改的表单界面  此时刷新页面 会提示要登录

http://localhost:9090/msg/add
http://localhost:9090/msg/modify/99070020

**Comment by kenberkeley** [comment]
明白。这个问题需要通过 cookie / localStorage / sessionStorage 解决。由于判断是否登录是基于 xhr 请求，因此毫无疑问是会出现这种状况的。日后可以改造成服务端吐出 session 到模板中，这样就可以避免这个问题。当前为了简单，并没有这样做。

**Comment by kenberkeley** [comment]
另见 [vue-demo issue#8](https://github.com/kenberkeley/vue-demo/issues/8)
