### ISSUE TITLE
问题咨询

### ISSUE THREAD

**Issue by ghost** [kenberkeley/react-demo#6]
你好，十一快乐。有个不请之请，公司打算节后做个后台系统，比较复杂的那种。这个项目目前是我一个人去做，项目选型我来定，我打算用react+redux+react-router-webpack+antd来做，希望思路上可以得到你的帮助。我qq：840690384，麻烦加下我，谢谢。（本来是想加你，考虑到你不方便贴自己qq）

**Comment by kenberkeley** [comment]
若是有关本 demo 的问题，可以直接在 issue 提出，我会尽快予您答复。
