### ISSUE TITLE
此项目基础上加上antd框架

### ISSUE THREAD

**Issue by ghost** [kenberkeley/react-demo#7]
1、安装antd
npm install --save-dev antd
2、在.babelrc的plugins里：
"plugins": [
    "transform-runtime",
    "transform-decorators-legacy",
    "antd"
   ]
3、npm start 后就报错了，麻烦看下怎么结合antd，谢谢

**Comment by kenberkeley** [comment]
由于问题已经超出本 demo 范畴，因此希望您可以通过搜索报错信息自行解决

> 温馨提示：框架 / 类库 须分离打包以加快开发时的编译速度并有利于缓存，详见 `build/webpack.base.conf.js` 中的 `vendor`
