### ISSUE TITLE
您好，我下载了您的项目，但是运行出现这样的错误

### ISSUE THREAD

**Issue by gelamo** [kenberkeley/react-demo#8]
mainifest.js:586 Uncaught TypeError: Cannot read property 'call' of undefined
127.0.0.1/:16947 Uncaught TypeError: **webpack_require**(...) is not a function
您好，我是初学者，对于webpack配置不是很熟，网上的教程也没有您的复杂，出现错误之后，想要直接打包，使用webpack的devtool工具，但是始终无法出现dist文件。请问具体webpack如何改，才能直接可以打包出文件，还有直接使用w7附带的CMD打开两个窗口也能运行嘛？请指点一下

**Comment by kenberkeley** [comment]
我刚才特意重新下载部署，没有发现问题。因此建议您提供更详细的信息。

**Comment by gelamo** [comment]
您好，npm start之后，为什么没有出现dist文件呢？请指点下

**Comment by kenberkeley** [comment]
建议您认真查看文档。`npm run build` 才是部署

**Comment by gelamo** [comment]
是的，因为我也试过部署，但是似乎出现的问题更多，就象这样file:///D:/static/bootstrap/css/bootstrap.min.css Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///D:/static/jquery.min.js Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///D:/static/bootstrap/js/bootstrap.min.js Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///D:/static/mainifest.1033d95d48dc4aa4b5e3.js Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///D:/static/vendor.10242296732f085c53dc.js Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///D:/static/app.a029ad98f69a179de39b.js Failed to load resource: net::ERR_FILE_NOT_FOUND

**Comment by gelamo** [comment]
我想知道根据您的配置，如何在开发环境下，直接打包文件，请指点下吗，不胜感激

**Comment by kenberkeley** [comment]
开发环境下，每次保存后均需要重新打包跑 IO，效率较低
而 Webpack 在开发环境下，编译后存放于内存，效率较高

您的这个需求大概是因为开发团队由后端主导
建议您自行配置代理服务器解决该问题

**Comment by gelamo** [comment]
您好，我的意思时，因为您的项目在我的电脑上出现了错误，我希望可以直接定位到具体的地方，所以希望可以直接打包，然后根据deltool配置来定位，就是一开始出现的错误mainifest.js:586 Uncaught TypeError: Cannot read property 'call' of undefined，定位到这句：
modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));

**Comment by kenberkeley** [comment]
开发环境下 Webpack 编译后的文件存于内存，您只能通过浏览器的开发工具（例如 Chrome 的 Sources）排查

**Comment by kenberkeley** [comment]
谷歌了一下，貌似有插件提供该支持：https://github.com/gajus/write-file-webpack-plugin

**Comment by gelamo** [comment]
谢谢啊，万分感谢
