### ISSUE TITLE
npm start 报错

### ISSUE THREAD

**Issue by SansaZhang** [kenberkeley/react-demo#9]
![image](https://cloud.githubusercontent.com/assets/8520011/19434090/2302cc00-9496-11e6-8370-8e13eb58658d.png)

在msg-board-api文件夹下安装的时候提示这样的错误，一开始 not found ‘express’ 安装之后又提示别的 ，这是什么情况？

**Comment by kenberkeley** [comment]
建议删除 `node_modules` 后重新 `cnpm i`

**Comment by SansaZhang** [comment]
恩，好了
